[package]
name = "differential-replay"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
call-api = { path = "../call-api" }
call-bridge = { path = "../call-bridge" }
call-core = { path = "../call-core" }
media-core = { path = "../media-core" }
scenario-replay = { path = "../scenario-replay" }
sdp = { path = "../sdp" }
sip-types = { path = "../sip-types" }
sip-parser = { path = "../sip-parser" }

[dev-dependencies]
call-engine = { path = "../call-engine" }
sip-transaction = { path = "../sip-transaction" }

[lints]
workspace = true
