[package]
name = "call-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
call-core = { path = "../call-core" }
sip-dialog = { path = "../sip-dialog" }

[dev-dependencies]
sip-types = { path = "../sip-types" }

[lints]
workspace = true
