[package]
name = "call-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
call-api = { path = "../call-api" }
call-core = { path = "../call-core" }
sip-dialog = { path = "../sip-dialog" }
sdp = { path = "../sdp" }
sip-transaction = { path = "../sip-transaction" }
sip-types = { path = "../sip-types" }

[lints]
workspace = true
